# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 0 * * 0-6"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # - name: Build Part 1
    #   run: |
    #     cd part1
    #     pwd
    #     go build -v -race -run TestElectionFollowerComesBack |& tee /tmp/raftlog

    - name: Test Part 1
      run: |
        cd part1
        pwd
        go test -v -race -run TestElectionFollowerComesBack |& tee /tmp/raftlog
        go run ../tools/raft-testlog-viz/main.go < /tmp/raftlog

    - name: Upload artifact for Test Part 1
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ./results/TestElectionFollowerComesBack.html

    - name: Test Part 2
      run: |
        cd part2
        pwd
        go test -race ./...
